{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "http-folder.serviceAccountName" . }}
  labels:
{{ include "http-folder.labels" . | indent 4 }}
{{- end -}}
